package fr.formation.inti.entity;
// Generated 18 janv. 2022 � 14:17:09 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department")
public class Department implements java.io.Serializable {

	private Integer deptId;
	private String name;

	public Department() {
	}

	public Department(String name) {
		this.name = name;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DEPT_ID", unique = true, nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

}
